---
# tasks file for node

- name: Assign cluster leader
  set_fact:
    cluster_leader: "{{ groups[group_names[0]][0] }}"

- name: Create Proxmox cluster '{{ proxmox_cluster_name }}'
  noahchalifour.pvecm.cluster:
    name: "{{ proxmox_cluster_name }}"
  when: inventory_hostname == cluster_leader

- name: Join the {{ proxmox_cluster_name }} cluster
  noahchalifour.pvecm.node:
    cluster: "{{ proxmox_cluster_name }}"
    leader: "{{ cluster_leader }}"
  when: inventory_hostname != cluster_leader
