---
# tasks file for node

- name: Assign cluster leader
  set_fact:
    cluster_leader: "{{ groups[group_names[0]][0] }}"

- name: Create Proxmox cluster '{{ proxmox_cluster_name }}'
  noahchalifour.pvecm.cluster:
    name: "{{ proxmox_cluster_name }}"
  when: inventory_hostname == cluster_leader

- name: Set up non-leader nodes
  block:
    - name: Ensure SSH keypair exists
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_path }}"
        type: ed25519
        owner: root
        group: root
        mode: "0600"
      register: ssh_keypair_result

    - name: Fetch public key
      ansible.builtin.slurp:
        src: "{{ ssh_key_path }}.pub"
      register: pubkey_contents

    - name: Install public key on leader node
      ansible.builtin.authorized_key:
        user: root
        key: "{{ pubkey_contents['content'] | b64decode }}"
      delegate_to: "{{ cluster_leader }}"

    - name: Join the {{ proxmox_cluster_name }} cluster
      noahchalifour.pvecm.node:
        cluster: "{{ proxmox_cluster_name }}"
        leader: "{{ cluster_leader }}"
  when: inventory_hostname != cluster_leader
